version: 2

workflows:
  version: 2
  validate:
    jobs:
      - tests
      - quality

jobs:
  tests:

    working_directory: /xblocker/app/

    docker:
      - image: python:3.6-alpine
      - image: mysql:5.7
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
        environment:
          MYSQL_ROOT_PASSWORD: ""
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

    environment:
      MYSQL_DATABASE: "xblocker_db"
      MYSQL_USER: "root"
      MYSQL_HOST: "127.0.0.1"
      MYSQL_PORT: 3306

    steps:

      - checkout

      - run:
          name: Install requirements
          command: |
            apk update && apk upgrade
            apk add bash bash-completion build-base git perl mariadb-dev
            python3.6 -m venv /xblocker/venv
            source /xblocker/venv/bin/activate
            make requirements

      - run:
          name: Run tests
          command: |
            source /xblocker/venv/bin/activate
            make test

  quality:

    working_directory: /xblocker/app/

    docker:
      - image: python:3.6-alpine

    steps:

      - checkout

      - run:
          name: Install requirements
          command: |
            apk update && apk upgrade
            apk add bash bash-completion build-base git perl mariadb-dev
            python3.6 -m venv /xblocker/venv
            source /xblocker/venv/bin/activate
            make requirements

      - run:
          name: Run quality
          command: |
            source /xblocker/venv/bin/activate
            make quality
